// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.CouchbaseExplorer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVsPackageString = "ef261503-b2ae-4b90-8c86-0becd83348cc";
        public static Guid guidVsPackage = new Guid(guidVsPackageString);

        public const string guidVsPackageCmdSetString = "715bc434-afd2-4104-a6a0-287120f718f5";
        public static Guid guidVsPackageCmdSet = new Guid(guidVsPackageCmdSetString);

        public const string guidCouchbaseIconString = "5adaa369-1a0a-437f-bf63-f609baad46fb";
        public static Guid guidCouchbaseIcon = new Guid(guidCouchbaseIconString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CouchbaseExplorerWindowCommandId = 0x0100;
        public const int couchbaseIcon = 0x0001;
    }
}